### PR TITLE
fix circular dependency for AerospikePersistenceEntityIndexCreator

### PR DESCRIPTION
**Pull request by Aloren**

### CODE REVIEW

**Review by roimenashe — APPROVED** [review]

**Comment by Aloren** [comment]
Let's merge?
And also can you please release. I think it should be 3.4.0. WDYT?

**Comment by roimenashe** [comment]
> 

If we bump spring then it's definitely 3.4.0.
1 more thing before we merge and release 3.4.0, check the latest email, I think that we need to bump spring-data-parent, spring-data-commons and spring-data-keyvalue as well (from 2.5.6 to 2.6.3 [latest]), am I missing something?

**Comment by Aloren** [comment]
Thanks. Will check now which spring-data-parent is expected to come with SB 2.6

**Comment by Aloren** [comment]
All 3 PRs for spring-data-* updates need to be merged as well.

**Comment by roimenashe** [comment]
> All 3 PRs for spring-data-* updates need to be merged as well.

@Aloren do you want to add it to this PR? since you are already upgrading `spring-cloud-starter-bootstrap` and `spring-boot-starter-test`?

**Comment by Aloren** [comment]
let's merge them separately:
https://github.com/aerospike-community/spring-data-aerospike/pull/350
https://github.com/aerospike-community/spring-data-aerospike/pull/351
https://github.com/aerospike-community/spring-data-aerospike/pull/352

**Comment by Aloren** [comment]
>since you are already upgrading spring-cloud-starter-bootstrap and spring-boot-starter-test?
I've upgraded them, because they were causing an issue that is fixed in this PR.

**Pull request merged**
