### PR TITLE
Add develop branch to the build

### PR DESCRIPTION
**Pull request by reugn**

### CODE REVIEW

**Comment by Aloren** [comment]
I would rather suggest sticking to github flow instead of git flow. Git flow is more complex and there is no reason for it in such a simple project.

**Comment by Aloren** [comment]
there is a nice blog post on this topic: http://scottchacon.com/2011/08/31/github-flow.html Please have a look

**Comment by reugn** [comment]
I agree. The development branch is for our internal reviews. We'll ditch it and eventually return to the github flow.

**Comment by Aloren** [comment]
I don’t see any issues with you working on a master branch. Creating develop branch now will give you more psychological freedom to push broken or untested features, which will definitely catch you later...

**Comment by reugn** [comment]
We'll work directly with master. Closing this PR.

**Pull request closed without merging**
