### PR TITLE
Move testcontainers bootstrap properties to test resources

### PR DESCRIPTION
**Pull request by jnopnop**
+ fix docker image version, since 5.5.0.3 and newer fail checksum validation

### CODE REVIEW

**Comment by roimenashe** [comment]
@jnopnop 
Thanks for creating this PR.
Can you please provide more information about this issue? fails where? under which circumstances?
5.5.0.3 is being used more than a year and tests completes successfully.

**Comment by jnopnop** [comment]
@roimenashe, this is what I'm getting when trying to pull `5.5.0.3`:
```
% docker pull aerospike/aerospike-server:5.5.0.3  
5.5.0.3: Pulling from aerospike/aerospike-server
cae7303ade7f: Verifying Checksum 
aca507f16e13: Verifying Checksum 
829a4d716723: Download complete 
daeb228a2a38: Download complete 
filesystem layer verification failed for digest sha256:aca507f...
```

Unfortunately newer versions fail checksum validation as well. However `5.5.0.2` works like a charm.

Just to be clear, the main goal of this PR is to move `bootstrap.properties` to the test resources, where they belong. 
Aerospike container version is the second [optional] question. I can of course leave the current one, but it just doesn't work.
WDYT?

**Comment by reugn** [comment]
@jnopnop the image is available, and you should be able to pull it. Try to restart your docker daemon and remove Aerospike images before.

**Comment by Aloren** [comment]
The main issue is `spring-data-aerospike` providing it's test properties in production resources, thus overriding user properties.
@jnopnop please revert change with the version and leave only moving of the `bootstrap.properties` file to the test resources folder.

**Comment by jnopnop** [comment]
✅

**Review by roimenashe — APPROVED** [review]

**Comment by roimenashe** [comment]
@jnopnop 
You'r PR is approved, you can merge it (and delete branch).

**Comment by jnopnop** [comment]
@roimenashe, I don't have permissions to merge, could you please do it? 
Thanks!

**Pull request merged**
