### PR TITLE
Throw exception when calling putAndGetHeader on a document with no bins + @_class bin disabled.

### PR DESCRIPTION
**Pull request by roimenashe**
Calling putAndGetHeader on a document with no bins + @_class bin disabled.

Previously NullPointerException was encountered.

### CODE REVIEW

**Comment by Aloren** [comment]
Shouldn't we allow saving empty record?

**Comment by roimenashe** [comment]
> Shouldn't we allow saving empty record?

@Aloren Not if you remove @_class bin, currently you will encounter NPE - we just want to make sure that it is clear.

**Comment by Aloren** [comment]
So if @_class bin removed and we cannot save empty bins -- this is a bug. We should not block users from saving empty bins. Do you have any reasons why we should?

**Comment by roimenashe** [comment]
@Aloren 
Aerospike doesn't support a record without a `bin`, it is not a Spring Data Aerospike limitation but we can at least throw a more self explanatory exception than a `NullPointerException`.

**Review by reugn — APPROVED** [review]

**Pull request merged**
