### PR TITLE
Add the OptimisticLockingFailureException throwing on the GENERATION_ERROR.

### PR DESCRIPTION
**Pull request by emax19**

### CODE REVIEW

**Review by reugn — APPROVED** [review]

**Comment by Aloren** [comment]
Please specify what is the reason for the change. Cas error is handled properly inside `AerospikeTemplate`: https://github.com/aerospike-community/spring-data-aerospike/blob/main/src/main/java/org/springframework/data/aerospike/core/BaseAerospikeTemplate.java#L162-L168
For concurrent version-aware saves not only generation-error may result into optimistic locking failure, so please describe what is the issue you are trying to solve.

**Comment by emax19** [comment]
> For concurrent version-aware saves not only generation-error may result in optimistic locking failure, so please describe what is the issue you are trying to solve.

The generation-error is always about concurrent version-aware save

The case is that I want to reuse aerospike spring components like the Aerospike `Client`, `ExceptionTranslator`, `Converters` but not the `Template` because it creates an additional restriction. 

In the implementation shared above, there is thrown OptimisticLockingException, and the logic related with how the AerospikeTemplate builds the WritePolicy and it used only for the `put` operations. In my case I want to use WritePolicy UPDATE and work with `map` operations, I don't care about was the entity created or not like it is specified in `Template`

To use the handling aerospike exception looks smelly because we have the `Translator` for this purpose. And if we know that `generation-error` is always about concurrent version-aware save - let's declare that. Other cases - it is a specific implementation as in example what you shared.

**Comment by Aloren** [comment]
> The generation-error is always about concurrent version-aware save

Yes, but not only. 
Adding such code results in:
1. Understanding by the end user that only generation error may result in `OptimisticLockingFailureException`, but this is not true. 
2. Having unused production code, not supported by any use-cases of the spring-data itself (this is because translation for the generation error is not done here, but instead is done in `AerospikeTemplate`).

>In my case I want to use WritePolicy UPDATE and work with map operations, I don't care about was the entity created or not like it is specified in Template

You are missing concurrent create, that needs to be handled accordingly as well: [RecordExistsAction.UPDATE](https://javadoc.io/doc/com.aerospike/aerospike-client/latest/com/aerospike/client/policy/RecordExistsAction.html#UPDATE) creates and updates the record, when using generation -- concurrent create and and concurrent update error must both result in `OptimisticLockingFailureException`.

> The case is that I want to reuse aerospike spring components like the Aerospike Client, ExceptionTranslator, Converters but not the Template because it creates an additional restriction.

Please elaborate more on what exactly you are doing -- what operation are you lacking?

**Comment by emax19** [comment]
> You are missing concurrent create, that needs to be handled accordingly as well: RecordExistsAction.UPDATE creates and updates the record, when using generation -- concurrent create and and concurrent update error must both result in OptimisticLockingFailureException.

When I use `UPDATE`/`REPLACE` policies, I can't get the `KEY_EXISTS_ERROR`
___
> 1. Understanding by the end user that only generation error may result in OptimisticLockingFailureException, but this is not true

That is true when we use `UPDATE`/`REPLACE` policies, other cases - are specific usage of the aerospike client.
___
> 2. Having unused production code, not supported by any use-cases of the spring-data itself (this is because translation for the generation error is not done here, but instead is done in AerospikeTemplate).

I agree with that. So, let's use that in the production code.

https://github.com/aerospike-community/spring-data-aerospike/blob/38cb5b33be83099a7e957326d629eaf667a08fd7/src/main/java/org/springframework/data/aerospike/core/BaseAerospikeTemplate.java#L181-L187

This production code can be rewritten to the next
```
    WritePolicy expectGenerationCasAwareSavePolicy(AerospikeWriteData data) {
        return expectGenerationSavePolicy(data, RecordExistsAction.REPLACE);
    }
```
So, you will have never got the `KEY_EXISTS_ERROR` and we will be able to say that the only `GENERATION_ERROR` can produce the `OptimisticLockingFailureException` in the spring data case.

**Pull request closed without merging**
